### ISSUE TITLE
Burger menu still visible on smaller screens, when no menu is available

### ISSUE THREAD

**Issue by suterma** [ThemeZee/chronus#1]
I am using the chronus theme for a simple "logger" site. I have no menu items and no menus, even no pages, just posts. Still, when having a small width (on smaller devices) the burger menu shows up. Nothing can be clicked of course.

I have fixed it for myself with this CSS:

```
/* no menu */
#main-navigation-wrap {
	display: none;
}
```
However, I suggest, you handle that edge case somewhere appropriate in the php code.

**Comment by Netzberufler** [comment]
Fixed now :)
